project_path = "/home/semyon/PycharmProjects/DiplomaPython"
source_path = "/home/semyon/PycharmProjects/DiplomaPython/source"
test_path = "/home/semyon/PycharmProjects/DiplomaPython/test"
data_path = "/home/semyon/PycharmProjects/DiplomaPython/data"
output_path = "/home/semyon/PycharmProjects/DiplomaPython/output"
