project_path = '/home/semyon/mipt/GPCR-TEAM/DiplomaPython/'
source_path = '/home/semyon/mipt/GPCR-TEAM/DiplomaPython/source/'
test_path = '/home/semyon/mipt/GPCR-TEAM/DiplomaPython/test/'
data_path = '/home/semyon/mipt/GPCR-TEAM/DiplomaPython/data/'
output_path = '/home/semyon/mipt/GPCR-TEAM/DiplomaPython/output/'
